AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 instance
Resources:              
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - 
          sg-036d1fa788e9d58a6
        - 
          sg-09feb76a01b90918e
      ImageId: ami-098f16afa9edf40be
      SubnetId: subnet-f19c8d96
      KeyName: ltsupport
      UserData:
          !Base64 |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl enable --now httpd
          useradd admin
          echo "RedHat@1" | passwd admin --stdin
          echo "#granting user admin root privileges" >> /etc/sudoers
          echo "admin  ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
          sed -i "s/.*PasswordAuthentication.*/PasswordAuthentication yes/g" /etc/ssh/sshd_config
          sed -i "s/ssh_pwauth:   0/ssh_pwauth:   1/g" /etc/cloud/cloud.cfg
          systemctl restart sshd
      Tags:
        - Key: Name
          Value: 'dev-EC2'           
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicIp 
